language: python
python:
  - 2.7
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libgeoip-dev
install:
    - pip install -r requirements.txt
    - python setup.py install
    - python script/bootstrap
script:
    - python script/test
